webapp/app/customer/forms.py
# -*- encoding: utf-8 -*-

from flask.ext.wtf import Form
from wtforms import (StringField, SubmitField, FloatField,
                        TextField, SelectField, PasswordField)
from wtforms.validators import (Required, Email,
                                    Length, EqualTo, Optional)

class RegisterForm(Form):
    org = StringField('org', validators=[Required()])
    name = StringField('name', validators=[Required()])
    labs = SelectField('labs', choices=[('', u'โปรดกรอกชื่อหน่วยงาน')],
            validators=[Required()])
    addlab = StringField('addlab', validators=[Required()])
    lastname = StringField('lastname', validators=[Required()])
    email = StringField('email', validators=[Required(), Email()])
    password = PasswordField('password',
            validators=[EqualTo('password2'), Required()])
    password2 = PasswordField('password', validators=[Required()])
    submit = SubmitField('Submit')


class ResultForm(Form):
    program_id = StringField('Program ID', validators=[Required()])

    # these info should be pull from db in the future
    methods = {
        'albumin': ['BCG', 'BCP', 'Vitros'],
        'alp': ['PNP AMP buff; IFCC', 'PNP AMP Buff; AACC',
            'PNP DEA buff; DGKC',
            'Vitros', 'Reflotron',
            'Beckman'],
        'alt': ['Kinetic37C/Kinetic-without pyridoxal',
            'Kinetic-pyridoxal',
            'Dade Behring',
            'Vitros',
            'Reflotron',
            'Beckman'],
        'ast': ['Kinetic37C/Kinetic-without pyridoxal',
            'Kinetic-pyridoxal',
            'Dade Behring',
            'Vitros',
            'Reflotron',
            'Beckman'],
        'bun': ['Enzyme Kinetic', 'Enzyme', 'Vitros', 'Reflotron'],
        'bilirubin': ['Jendrassik-Grof', 'Malloy-Evelyn', 'Vitros', 'Reflotron',
            'DCA/DPD', 'Diazonium'],
        'calcium': ['CPC/Asenazo', 'Vitros', 'ISE'],
        'chloride': ['Direct ISE', 'Indirect ISE', 'Vitros ISE', 'Reflotron'],
        'cholesterol': ['Enzyme Colorimetric', 'Vitros', 'Reflotron',
            'Dade Behring', 'Beckman'],
        'ck': ['CK-NAC/IFCC', 'Colorimetric', 'Vitros', 'Reflotron'],
        'creatinine': ['Jaffe Kinetic', 'Jaffe EP', 'Vitros', 'Enzyme',
            'Reflotron'],
        'ggt': ['Enzyme Kinetic', 'Enzyme Colorimetric', 'Dade Behring',
            'Vitros', 'Reflotron'],
        'glucose': ['GOD', 'HK', 'Vitros', 'Reflotron', 'GDH'],
        'hdl_chol': ['Direct Determination',
            'Phospho. Precip./Polyanion', 'Vitros',
            'Imm. Inhibition', 'Others'],
        'ldh': ['IFCC', 'SSCC', 'DGKC', 'Vitros', 'Beckman'],
        'ldl_chol': ['Direct Determination', 'Others'],
        'P': ['Molybdenum EP', 'Molybdenum UV', 'Vitros'],
        'K': ['Direct ISE', 'Indirect ISE', 'Vitros', 'Reflotron'],
        'protein': ['Biuret-Blank', 'Biuret-Unblank', 'Vitros'],
        'Na': ['Direct ISE', 'Indirect ISE', 'Vitros', 'Reflotron'],
        'trig': ['Enzyme Color Total TG', 'Glycerol Blank', 'Vitros',
            'Reflotron', 'Dade Behring'],
        'uric': ['Enzyme EP Blank', 'Enzyme EP Unblank', 'Vitros', 'Reflotron',
            'Dade Behring'],
    }

    albumin = FloatField('Albumin', validators=[Optional()])
    albumin_ = SelectField('albumin_method',
           choices=[(m,m) for m in methods['albumin']]
           )
    alp = FloatField('ALP', validators=[Optional()])
    alp_ = SelectField('alp_method',
           choices=[(m,m) for m in methods['alp']]
           )
    alt = FloatField('ALT (SGPT)', validators=[Optional()])
    alt_ = SelectField('alt_method',
           choices=[(m,m) for m in methods['alt']]
           )
    ast = FloatField('AST (SGOT)', validators=[Optional()])
    ast_ = SelectField('ast_method',
           choices=[(m,m) for m in methods['ast']]
           )
    bun = FloatField('BUN', validators=[Optional()])
    bun_ = SelectField('bun_method',
            choices=[(m,m) for m in methods['bun']]
            )
    bilirubin = FloatField('Bilirubin, Total', validators=[Optional()])
    bilirubin_ = SelectField('bilirubin_method',
           choices=[(m,m) for m in methods['bilirubin']]
           )
    calcium = FloatField('Calcium, Total', validators=[Optional()])
    calcium_ = SelectField('calcium_method',
           choices=[(m,m) for m in methods['calcium']]
           )
    chloride = FloatField('Chloride', validators=[Optional()])
    chloride_ = SelectField('chloride_method',
           choices=[(m,m) for m in methods['chloride']]
           )
    cholesterol = FloatField('Cholesterol', validators=[Optional()])
    cholesterol_ = SelectField('cholesterol_method',
           choices=[(m,m) for m in methods['cholesterol']]
           )
    ck = FloatField('CK, Total', validators=[Optional()])
    ck_ = SelectField('ck_method',
           choices=[(m,m) for m in methods['ck']]
           )
    creatinine = FloatField('Creatinine', validators=[Optional()])
    creatinine_ = SelectField('creatinine_method',
           choices=[(m,m) for m in methods['creatinine']]
           )
    ggt = FloatField('GGT', validators=[Optional()])
    ggt_ = SelectField('ggt_method_method',
           choices=[(m,m) for m in methods['ggt']]
           )
    glucose = FloatField('Glucose', validators=[Optional()])
    glucose_ = SelectField('glucose_method',
           choices=[(m,m) for m in methods['glucose']]
           )
    hdl_chol = FloatField('HDL-Cholesterol', validators=[Optional()])
    hdl_chol_ = SelectField('hdl_chol_method',
           choices=[(m,m) for m in methods['hdl_chol']]
           )
    ldh = FloatField('LDH', validators=[Optional()])
    ldh_ = SelectField('ldh_method',
           choices=[(m,m) for m in methods['ldh']]
           )
    ldl_chol = FloatField('LDL-Cholesterol', validators=[Optional()])
    ldl_chol_ = SelectField('ldl_chol_method',
           choices=[(m,m) for m in methods['ldl_chol']]
           )
    P = FloatField('Phosphorus', validators=[Optional()])
    P_ = SelectField('P_method',
           choices=[(m,m) for m in methods['P']]
           )
    K = FloatField('Potassium', validators=[Optional()])
    K_ = SelectField('K_method',
           choices=[(m,m) for m in methods['K']]
           )
    protein = FloatField('Protein, Total', validators=[Optional()])
    protein_ = SelectField('protein_method',
           choices=[(m,m) for m in methods['protein']]
           )
    Na = FloatField('Sodium', validators=[Optional()])
    Na_ = SelectField('Na_method',
           choices=[(m,m) for m in methods['Na']]
           )
    trig = FloatField('Triglycerides', validators=[Optional()])
    trig_ = SelectField('trig_method',
           choices=[(m,m) for m in methods['trig']]
           )
    uric = FloatField('Uric acid', validators=[Optional()])
    uric_ = SelectField('uric_method',
            choices=[(m,m) for m in methods['uric']]
            )
    comment = TextField('Comment', validators=[Optional()])
    submit = SubmitField('Submit')

webapp/app/customer/__init__.py
from flask import Blueprint

customer = Blueprint('customer', __name__)

from . import views

webapp/app/customer/views.py
# -*- coding: utf-8 -*-

from flask import render_template, redirect, url_for, flash, jsonify, request
from flask.ext.login import current_user, logout_user
from .forms import RegisterForm, ResultForm
from . import customer
from .. import mongo
from bson import json_util
from werkzeug.security import generate_password_hash
from datetime import datetime
from ..models import get_result_id
import numpy as np

@customer.route('/getlabs')
def get_labname():
    org = request.args.get('org', 'unknown')
    labs = [o['labname']
            if o else '' for o in mongo.db.orgs.find({'name': org})]
    return jsonify(labs=labs)

@customer.route('/register', methods=['POST', 'GET'])
def register():
    if current_user.is_authenticated():
        logout_user()

    form = RegisterForm()
    orgs = {'source': sorted([x.get('name')
                    for x in mongo.db.orgs.find()], key=lambda x: x[0])}

    if form.validate_on_submit():
        if form.org.data != '':
            new_org = None
        else:
            new_org = form.new_org.data

        new_customer = {
                'name': form.name.data,
                'lastname': form.lastname.data,
                'password': generate_password_hash(form.password.data),
                'org': form.org.data or None,
                'new_org': new_org,
                'email': form.email.data,
                }

        mongo.db.customers.insert(new_customer, safe=True)
        return redirect(url_for('auth.login'))

    return render_template('/customers/register.html',
            form=form,
            orgs=orgs)

@customer.route('/results_1', methods=['POST', 'GET'])
def results():
    form = ResultForm()
    if form.validate_on_submit():
        # TODO: need to look up program id from the db
        result_id = get_result_id(form.program_id.data)

        new_results = {
            'entered_at': datetime.now(),
            'entered_by': current_user.email,
            'program_id': form.program_id.data,
            'comment': form.comment.data,
            'subprogram': 1,
            'result_id': result_id,

            'albumin' : form.albumin.data,
            'alp' : form.alp.data,
            'alt' : form.alt.data,
            'ast' : form.ast.data,
            'bun' : form.bun.data,
            'bilirubin' : form.bilirubin.data,
            'calcium' : form.calcium.data,
            'chloride' : form.chloride.data,
            'cholesterol' : form.cholesterol.data,
            'ck' : form.ck.data,
            'creatinine' : form.creatinine.data,
            'ggt' : form.ggt.data,
            'glucose' : form.glucose.data,
            'hdl_chol' : form.hdl_chol.data,
            'ldh' : form.ldh.data,
            'ldl_chol' : form.ldl_chol.data,
            'P' : form.P.data,
            'K' : form.K.data,
            'protein' : form.protein.data,
            'Na' : form.Na.data,
            'trig' : form.trig.data,
            'uric' : form.uric.data,
            # Fields below are for future use.
            #'edited_at': datetime.now()
            'albumin_method' : form.albumin_.data,
            'alp_method' : form.alp_.data,
            'alt_method' : form.alt_.data,
            'ast_method' : form.ast_.data,
            'bun_method' : form.bun_.data,
            'bilirubin_method' : form.bilirubin_.data,
            'calcium_method' : form.calcium_.data,
            'chloride_method' : form.chloride_.data,
            'cholesterol_method' : form.cholesterol_.data,
            'ck_method' : form.ck_.data,
            'creatinine_method' : form.creatinine_.data,
            'ggt_method' : form.ggt_.data,
            'glucose_method' : form.glucose_.data,
            'hdl_chol_method' : form.hdl_chol_.data,
            'ldh_method' : form.ldh_.data,
            'ldl_chol_method' : form.ldl_chol_.data,
            'P_method' : form.P_.data,
            'K_method' : form.K_.data,
            'protein_method' : form.protein_.data,
            'Na_method' : form.Na_.data,
            'trig_method' : form.trig_.data,
            'uric_method' : form.uric_.data,
        }

        mongo.db.results.insert(new_results, safe=True)
        flash('Results number %s has been successfully saved to the database.'
                % str(result_id))
        return redirect(url_for('.results'))
    return render_template('/customers/results.html', form=form)

@customer.route('/report/<progid>')
def report(progid):
    # test_methods = set()
    # for r in mongo.db.results.find():
    #     if r[test_method]:
    #         test_methods.add(r[test_method])

    # test_values = {}
    # for m in test_methods:
    #     tests = []
    #     for r in mongo.db.results.find({test_method: m}):
    #         if r[test_name]:
    #             tests.append(r[test_name])
    #     test_values[m] = tests

    # all_methods = []

    def calculate(values, sd_range):
        mean = np.mean(values)
        std = np.std(values)
        N = len(values)
        CV = std/mean * 100.0
        upper = mean + sd_range * std
        lower = mean - sd_range * std
        return {'mean': mean,
                'std': std,
                'N': N,
                'CV': CV,
                'upper': upper,
                'lower': lower,
                'test_name': test_name}


    # def filter_values(values, sd_range):
    #     """Returns values within std range"""
    #     mean = np.mean(values)
    #     std = np.std(values)
    #     upper = mean + (sd_range * std)
    #     lower = mean - (sd_range * std)
    #     filtered_values = []
    #     for val in values:
    #         if upper >= val >= lower:
    #             filtered_values.append(val)

    #     return filtered_values


    # for m in test_methods:
    #     calculate(test_values[m], m, 1.5)
    #     all_methods += test_values[m]

    # principle = "All"
    values = []
    test_name = 'glucose'
    for r in mongo.db.results.find():
        val = r[test_name]
        #TODO: rewrite this line to honor 0
        if val:
            values.append(val)


    stats = calculate(values, 1.5)
    cust_res = mongo.db.results.find_one({'program_id': progid})
    cust_gluc = cust_res['glucose']
    print stats

    # for m in test_methods:
    #     filtered_values = filter_values(test_values[m], 3)
    #     calculate(filtered_values, 'New ' + m, 1.5)

    # filtered_values = filter_values(all_methods, 3)
    # calculate(filtered_values, 'New all', 1.5)

    return render_template('/customers/report.html', stats=stats,
            cust_gluc=cust_gluc)

webapp/app/templates/customers/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Register {% endblock %}

{% block scripts %}
{{ super() }}
<script type="text/javascript">
    $SCRIPT_ROOT = {{ request.script_root|tojson|safe }}

    $(document).ready(function() {
            $('#addlab').on('focus', function() {
                if($('#labs').val().length == 0) {
                    $('#addlab').prop('disabled', false);
                } else {
                    $('#addlab').prop('disabled', true);
                }
            });

            $('#org').autocomplete({{ orgs|tojson|safe }});
            $('#org').on('autocompleteselect', function(event, ui) {
                $('#org').val(ui.item.value);
                event.preventDefault();

                $('#labs option').each(function() { $(this).remove() });

                $.getJSON($SCRIPT_ROOT + '/customer/getlabs', {
                    org: $('#org').val()
                },
                function(data) {
                data.labs.map(function(item) {
                    $('#labs').append('<option value=' + item + '>' + item + '</option>')
                    })
                });

                {# $('#labs').val($('#labs option').eq(0).val()); #}

                {# if($('#labs').val().length == 0) { #}
                {#     $('#addlab').prop('disabled', false); #}
                {# } else { #}
                {#     $('#addlab').prop('disabled', true); #}
                {# } #}
            });
    });
</script>
{% endblock %}
{% block page_content %}
<div class="page-header">
    <h1>Registeration Form</h1>
</div>
<div class="col-md-12">
    <form method="POST" action="{{ url_for('customer.register') }}">
        {{ form.hidden_tag()  }}
        <div class="panel panel-primary">
            <div class="panel panel-heading"><h3 class="panel-title">สมัครสมาชิกเพื่อใช้งานเว็บ</h3></div>
            <div class="panel-body">
                <strong>ชื่อหน่วยงานที่สังกัด</strong> {{ form.org(size=50) }} <small>(กรุณาพิมพ์ชื่อเพื่อค้นหา)</small>
                <br/>
                <br/>
                <strong>Labs</strong> {{ form.labs() }}
                <br/>
                <br/>
                <strong>กรุณาใส่ชื้อแลบ</strong> {{ form.addlab() }}
                <br/>
                <br/>
                <strong>ชื่อผู้สมัคร</strong> {{ form.name(size=30) }}
                <strong>นามสกุล</strong> {{ form.lastname(size=30) }}
                <br/>
                <br/>
                <strong>อีเมล</strong> {{ form.email(size=30) }}
                <br/>
                <br/>
                <strong>รหัสผ่าน</strong> {{ form.password(size=30) }}
                <br/>
                <br/>
                <strong>รหัสผ่าน อีกครั้ง</strong> {{ form.password2(size=30) }}
            </div>
        </div>
        {{ form.submit }}
    </form>
</div>
{% endblock %}

webapp/app/templates/customers/results.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %} Enter Results {% endblock %}

{% block scripts %}
{{ super() }}
<script src="{{ url_for('static', filename="jquery-2.1.4.min.js") }}"></script>
<script src="{{ url_for('static', filename="js/chem-result-1.js") }}"></script>
{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Results Form EQAC.1</h1>
</div>
<div class="col-md-12">
    <form id="form" method="POST" action="{{ url_for('customer.results') }}">
        {{ form.hidden_tag()  }}
        <div class="panel panel-primary">
            <div class="panel panel-heading"><h3 class="panel-title">Temp Section</h3></div>
            <div class="panel-body">
                <strong>{{ form.program_id.label }}</strong> {{ form.program_id(size=20) }}
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel panel-heading"><h3 class="panel-title">All Tests</h3></div>
            <div class="panel-body">
                <table class="table table-hover">
                    <tr>
                        <td><strong>Test</strong></td>
                        <td><strong>Principle/Method/Instrument</strong></td>
                        <td><strong>Result</strong></td>
                        <td><strong>Unit</strong></td>
                    </tr>
                    <tbody>
                    <tr>
                        <td>{{ form.albumin.label }}</td>
                        <td>{{ form.albumin_() }}</td>
                        <td>{{ form.albumin() }}</td>
                        <td>g/dL</td>
                    </tr>
                    <tr>
                        <td>{{ form.alp.label }}</td>
                        <td>{{ form.alp_() }}</td>
                        <td>{{ form.alp() }}</td>
                        <td>U/L</td>
                    </tr>
                    <tr>
                        <td>{{ form.alt.label }}</td>
                        <td>{{ form.alt_() }}</td>
                        <td>{{ form.alt() }}</td>
                        <td>U/L</td>
                    </tr>
                    <tr>
                        <td>{{ form.ast.label }}</td>
                        <td>{{ form.ast_() }}</td>
                        <td>{{ form.ast() }}</td>
                        <td>U/L</td>
                    </tr>
                    <tr>
                        <td>{{ form.bun.label }}</td>
                        <td>{{ form.bun_() }}</td>
                        <td>{{ form.bun() }}</td>
                        <td>mg/dL</td>
                    </tr>
                    <tr>
                        <td>{{ form.bilirubin.label }}</td>
                        <td>{{ form.bilirubin_() }}</td>
                        <td>{{ form.bilirubin() }}</td>
                        <td>mg/dL</td>
                    <tr>
                        <td>{{ form.calcium.label }}</td>
                        <td>{{ form.calcium_() }}</td>
                        <td>{{ form.calcium() }}</td>
                        <td>mg/dL</td>
                    </tr>
                    <tr>
                        <td>{{ form.chloride.label }}</td>
                        <td>{{ form.chloride_() }}</td>
                        <td>{{ form.chloride() }}</td>
                        <td>mmol/L</td>
                    </tr>
                    <tr>
                        <td>{{ form.cholesterol.label }}</td>
                        <td>{{ form.cholesterol_() }}</td>
                        <td>{{ form.cholesterol() }}</td>
                        <td>mg/dL</td>
                    </tr>
                    <tr>
                        <td>{{ form.ck.label }}</td>
                        <td>{{ form.ck_() }}</td>
                        <td>{{ form.ck() }}</td>
                        <td>U/L</td>
                    </tr>
                    <tr>
                        <td>{{ form.creatinine.label }}</td>
                        <td>{{ form.creatinine_() }}</td>
                        <td>{{ form.creatinine() }}</td>
                        <td>mg/dL</td>
                    </tr>
                    <tr>
                        <td>{{ form.ggt.label }}</td>
                        <td>{{ form.ggt_() }}</td>
                        <td>{{ form.ggt() }}</td>
                        <td>U/L</td>
                    </tr>
                    <tr>
                        <td>{{ form.glucose.label }}</td>
                        <td>{{ form.glucose_() }}</td>
                        <td>{{ form.glucose() }}</td>
                        <td>mg/dL</td>
                    </tr>
                    <tr>
                        <td>{{ form.hdl_chol.label }}</td>
                        <td>{{ form.hdl_chol_() }}</td>
                        <td>{{ form.hdl_chol() }}</td>
                        <td>mg/dL</td>
                    </tr>
                    <tr>
                        <td>{{ form.ldh.label }}</td>
                        <td>{{ form.ldh_() }}</td>
                        <td>{{ form.ldh() }}</td>
                        <td>U/L</td>
                    </tr>
                    <tr>
                        <td>{{ form.ldl_chol.label }}</td>
                        <td>{{ form.ldl_chol_() }}</td>
                        <td>{{ form.ldl_chol() }}</td>
                        <td>mg/dL</td>
                    </tr>
                    <tr>
                        <td>{{ form.P.label }}</td>
                        <td>{{ form.P_() }}</td>
                        <td>{{ form.P() }}</td>
                        <td>mg/dL</td>
                    </tr>
                    <tr>
                        <td>{{ form.K.label }}</td>
                        <td>{{ form.K_() }}</td>
                        <td>{{ form.K() }}</td>
                        <td>mmol/L</td>
                    </tr>
                    <tr>
                        <td>{{ form.protein.label }}</td>
                        <td>{{ form.protein_() }}</td>
                        <td>{{ form.protein() }}</td>
                        <td>g/dL</td>
                    </tr>
                    <tr>
                        <td>{{ form.Na.label }}</td>
                        <td>{{ form.Na_() }}</td>
                        <td>{{ form.Na() }}</td>
                        <td>mmol/L</td>
                    </tr>
                    <tr>
                        <td>{{ form.trig.label }}</td>
                        <td>{{ form.trig_() }}</td>
                        <td>{{ form.trig() }}</td>
                        <td>mg/dL</td>
                    </tr>
                    <tr>
                        <td>{{ form.uric.label }}</td>
                        <td>{{ form.uric_() }}</td>
                        <td>{{ form.uric() }}</td>
                        <td>mg/dL</td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="panel panel-primary">
            <div class="panel panel-heading"><h3 class="panel-title">Comment</h3></div>
            <div class="panel-body">
                {{ form.comment(size=100) }}
            </div>
        </div>
        {{ form.submit }}
    </form>
</div>
{% endblock %}